menu:
  Home: /
  Archives: /archives

site_image: /images/Flower.jpg

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

facebook:
google_plus:
twitter:
github:

fancybox: true
excerpt_link: true
google_analytics:
rss:
