menu:
  Home: /
  Archives: /archives

site_image: /images/Flower.jpg

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

sharing:
  google_plus: true
  facebook: true

facebook_author:
facebook_page:
google_plus:
twitter:
github:

fancybox: true
gallery: true
excerpt_link: true
google_analytics:
rss:
